version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "pthungathurthi"
github_repo = "customer-service"
deployment_branch = "master"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[Test.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::183295410578:role/aws-sam-cli-managed-Test-pipe-PipelineExecutionRole-ePk7QoBYur4F"
cloudformation_execution_role = "arn:aws:iam::183295410578:role/aws-sam-cli-managed-Test--CloudFormationExecutionRo-TLnn5kIw3sAi"
artifacts_bucket = "aws-sam-cli-managed-test-pipeline--artifactsbucket-dfqhxk914ocm"
image_repository = ""
region = "ap-southeast-2"
